name: dolphinmusic
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 屏幕适配 
  flutter_screenutil: ^2.1.0
  # 本地缓存
  shared_preferences: ^0.5.7+3
  # 轻提醒
  bot_toast: ^3.0.0
  # 请求
  dio: ^3.0.9
  # cookie管理
  dio_cookie_manager: ^1.0.0
  # 
  path_provider: ^1.6.11
  # 路由管理
  fluro: ^1.6.3
  # 状态管理
  provider: ^4.1.3
  # 轮播图
  flutter_swiper: ^1.1.6
  # 折叠面板
  expandable: ^4.1.4
  flutter_zoom_drawer: "^1.0.4"
  # tab
  motion_tab_bar: ^0.1.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon_logo.png
    - assets/images/icon_daily.png
    - assets/images/icon_look.png
    - assets/images/icon_playlist.png
    - assets/images/icon_radio.png
    - assets/images/icon_rank.png
    - assets/images/icon_broadcast.png
    - assets/images/icon_collect.png
    - assets/images/icon_download_black.png
    - assets/images/icon_late_play.png
    - assets/images/icon_music.png
    - assets/images/dj_menber.png
    - assets/images/dj_rank.png
    - assets/images/dj_sort.png
    - assets/images/dj_study.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
